[package]
name = "stall"
version = "0.1.3"
authors = ["Skylor R Schermer <skyschermer@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/solarretrace/stall-rs"
description = "A simple local configuration management utility"
readme = "readme.md"
keywords = []
homepage = "https://github.com/solarretrace/stall-rs"
exclude = ["*.sublime-project", "*.sublime-workspace", ".stall"]

[lib]
name = "stall"

[features]
default = []

# Required dependencies
[dependencies]
rustc_version_runtime = "0.1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
structopt = { version = "0.3", features = ["suggestions", "color"] }
log = { version = "0.4", features = ["serde"] }
fern = { version = "0.6", features = ["colored"] }
ron = "0.6"
colored = "1.9"


# Optional dependencies

# Dependencies used for tests, examples, and benches.
[dev-dependencies]


# The development profile, used for `cargo build`
[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
incremental = true
overflow-checks = true

# Development profile overrides, ensure dependent crates run fast.
[profile.dev.package."*"]
opt-level = 3
debug-assertions = false
codegen-units = 1


# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 3
debug = true
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = true


